### ISSUE TITLE
[3.7] Syntax error when importing pydle; caused by a module called "async"

### ISSUE THREAD

**Issue by ViAik** [Shizmob/pydle#86] opened 2018-11-23 01:22 UTC
Since `async` was added as a keyword in Python 3.7, importing `async.py` as a module raises a syntax error. I resolved this by simply renaming the module to something else and editing pydle's source files accordingly. As of now, the library is unusable on 3.7 until the user renames that file.

**Comment by Harmon758** [comment] 2018-11-23 05:36
Duplicate of #76

**Comment by Shizmob** [comment] 2018-12-23 18:00
Fixed with the most recent merge, release pending!

**Closed by Shizmob** 2018-12-23 18:00 UTC
